image:
  file: .gitpod.Dockerfile

tasks:
  - name: Build and Test
    init: mvn clean install
    command: mvn test

ports:
  - port: 7900
    onOpen: ignore

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - formulahendry.code-runner
    - ritwickdey.liveserver
